/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.AsignarTarea;

import dto.TareaDTO;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import presentacion.controles.IControlCreacionUI;
import presentacion.controles.IControlMensajes;
import presentacion.controles.IControlNavegacion;
import presentacion.controles.IControlTareas;

/**
 *
 * @author Angel Servin
 */
public class PantallaElegirTarea extends javax.swing.JFrame {

    private final IControlTareas controlTareas;
    private final IControlMensajes mensajes;
    private final IControlCreacionUI creacion;
    private final IControlNavegacion navegacion;
    private final String idMecanico;

    private DefaultTableModel modeloTablaTareas;

    public PantallaElegirTarea(String idMecanico, IControlTareas controlTareas,
            IControlMensajes mensajes, IControlCreacionUI creacion,
            IControlNavegacion navegacion) {
        this.idMecanico = idMecanico;
        this.controlTareas = controlTareas;
        this.mensajes = mensajes;
        this.creacion = creacion;
        this.navegacion = navegacion;

        initComponents();
        configurarModeloTabla();
        estilizarTabla();
        cargarTareasSinAsignar();
        agregarListenerTabla();
    }

    private void configurarModeloTabla() {
        String[] columnas = {"ID", "Descripción", "Vehículo"};
        modeloTablaTareas = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaTareas.setModel(modeloTablaTareas);

        // Ocultar columna ID
        tablaTareas.getColumnModel().getColumn(0).setMinWidth(0);
        tablaTareas.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaTareas.getColumnModel().getColumn(0).setPreferredWidth(0);
        tablaTareas.getColumnModel().getColumn(0).setResizable(false);
    }

    private void estilizarTabla() {
        creacion.aplicarEstiloTabla(scrollPaneTareas, tablaTareas);
    }

    private void cargarTareasSinAsignar() {
        modeloTablaTareas.setRowCount(0);

        List<TareaDTO> tareas = controlTareas.obtenerTareasSinAsignar();

        for (TareaDTO t : tareas) {
            modeloTablaTareas.addRow(new Object[]{
                t.getIdTarea(),
                t.getDescripcion(),
                t.getVehiculoModelo()
            });
        }
    }

    private void agregarListenerTabla() {
        tablaTareas.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int fila = tablaTareas.getSelectedRow();
                    if (fila != -1) {
                        String idTarea = (String) modeloTablaTareas.getValueAt(fila, 0);
                        String descripcion = (String) modeloTablaTareas.getValueAt(fila, 1);

                        confirmarSeleccionTarea(idTarea, descripcion);
                    }
                }
            }
        });
    }

    private void confirmarSeleccionTarea(String idTarea, String descripcion) {
        Boolean confirmar = mensajes.mostrarConfirmacion(this,
                "¿Deseas asignar la tarea:\n" + descripcion + "\n al mecánico seleccionado?",
                "Confirmar Asignación");

        if (confirmar) {
            boolean exito = controlTareas.asignarTareaAMecanico(idTarea, idMecanico);
            if (exito) {
                mensajes.mostrarExito("Tarea asignada correctamente.");
                cargarTareasSinAsignar();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollPaneTareas = new javax.swing.JScrollPane();
        tablaTareas = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneTareas.setViewportView(tablaTareas);

        jPanel1.add(scrollPaneTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 150, 470, 210));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonRegresar.png"))); // NOI18N
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setDefaultCapable(false);
        btnRegresar.setFocusPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PantallaElegirTareas.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

    }//GEN-LAST:event_btnRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scrollPaneTareas;
    private javax.swing.JTable tablaTareas;
    // End of variables declaration//GEN-END:variables
}
