/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.AsignarTarea;

import dto.EmpleadoDTO;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import presentacion.controles.IControlCreacionUI;
import presentacion.controles.IControlEmpleados;
import presentacion.controles.IControlMensajes;
import presentacion.controles.IControlNavegacion;

/**
 *
 * @author Angel Servin
 */
public class PantallaElegirMecanico extends javax.swing.JFrame {

    private final IControlEmpleados controlEmpleados;
    private final IControlMensajes mensajes;
    private final IControlCreacionUI creacion;
    private final IControlNavegacion navegacion;

    private DefaultTableModel modeloTablaMecanicos;

    public PantallaElegirMecanico(IControlEmpleados controlEmpleados, IControlMensajes mensajes,
            IControlCreacionUI creacion, IControlNavegacion navegacion) {
        this.controlEmpleados = controlEmpleados;
        this.mensajes = mensajes;
        this.creacion = creacion;
        this.navegacion = navegacion;

        initComponents();
        configurarModeloTabla();
        estilizarTabla();
        cargarMecanicos();
        agregarListenerTabla();
    }

    private void configurarModeloTabla() {
        String[] columnas = {"ID", "Nombre", "Estado", "Rol"};
        modeloTablaMecanicos = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaMecanicos.setModel(modeloTablaMecanicos);

        // Ocultar columna ID completamente
        tablaMecanicos.getColumnModel().getColumn(0).setMinWidth(0);
        tablaMecanicos.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaMecanicos.getColumnModel().getColumn(0).setPreferredWidth(0);
        tablaMecanicos.getColumnModel().getColumn(0).setResizable(false);
    }

    private void estilizarTabla() {
        creacion.aplicarEstiloTabla(scrollPaneMecanicos, tablaMecanicos);
    }

    private void cargarMecanicos() {
        modeloTablaMecanicos.setRowCount(0);

        List<EmpleadoDTO> lista = controlEmpleados.obtenerMecanicosParaTabla();

        for (EmpleadoDTO m : lista) {
            modeloTablaMecanicos.addRow(new Object[]{
                m.getId_empleado(),
                m.getNombre() + " " + m.getApellidoP(),
                m.getActivo() ? "Activo" : "Inactivo",
                m.getRol()
            });
        }
    }

    private void agregarListenerTabla() {
        tablaMecanicos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int fila = tablaMecanicos.getSelectedRow();
                    if (fila != -1) {
                        String id = (String) modeloTablaMecanicos.getValueAt(fila, 0);
                        String nombre = (String) modeloTablaMecanicos.getValueAt(fila, 1);

                        confirmarSeleccionMecanico(id, nombre);
                    }
                }
            }
        });
    }

    private void confirmarSeleccionMecanico(String idMecanico, String nombre) {
        Boolean confirmar = mensajes.mostrarConfirmacion(this,
                "¿Deseas continuar con el mecánico:\n" + nombre + "?",
                "Confirmar Selección");

        if (confirmar) {
            navegacion.mostrarPantallaElegirTarea(idMecanico);
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creacionTablas1 = new presentacion.utilerias.CreacionTablas();
        jPanel1 = new javax.swing.JPanel();
        scrollPaneMecanicos = new javax.swing.JScrollPane();
        tablaMecanicos = new javax.swing.JTable();
        btnAtras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollPaneMecanicos.setMaximumSize(new java.awt.Dimension(32760, 32760));

        tablaMecanicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneMecanicos.setViewportView(tablaMecanicos);

        jPanel1.add(scrollPaneMecanicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 150, 470, 210));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonRegresar.png"))); // NOI18N
        btnAtras.setToolTipText("");
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.setDefaultCapable(false);
        btnAtras.setFocusPainted(false);
        btnAtras.setFocusable(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PantallaElegirMecanico.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        navegacion.mostrarMenuPrincipalAdmin();
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private presentacion.utilerias.CreacionTablas creacionTablas1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scrollPaneMecanicos;
    private javax.swing.JTable tablaMecanicos;
    // End of variables declaration//GEN-END:variables
}
