/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.VerHistorial;

import dto.EmpleadoDTO;
import dto.TareaDTO;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import presentacion.controles.IControlCreacionUI;
import presentacion.controles.IControlDocumentos;
import presentacion.controles.IControlMensajes;
import presentacion.controles.IControlNavegacion;
import presentacion.controles.IControlTareas;

/**
 *
 * @author Angel Servin
 */
public class PantallaVerHistorial extends javax.swing.JFrame {

    private final IControlNavegacion navegacion;
    private final IControlDocumentos controlDocumentos;
    private final IControlMensajes mensajes;
    private final IControlCreacionUI creacion;
    private final IControlTareas controlTareas;
    private final EmpleadoDTO mecanicoActual;

    private DefaultTableModel modeloTabla;

    public PantallaVerHistorial(IControlNavegacion navegacion,
            IControlMensajes mensajes,
            IControlCreacionUI creacion,
            IControlTareas controlTareas,
            IControlDocumentos controlDocumentos,
            EmpleadoDTO mecanicoActual) {

        this.navegacion = navegacion;
        this.mensajes = mensajes;
        this.creacion = creacion;
        this.controlTareas = controlTareas;
        this.controlDocumentos = controlDocumentos;
        this.mecanicoActual = mecanicoActual;

        initComponents();
        configurarModeloTabla();
        estilizarTabla();
        cargarHistorial();
        this.setLocationRelativeTo(null);
    }

    private List<TareaDTO> obtenerTareasDeLaTabla() {
        List<TareaDTO> lista = new ArrayList<>();

        int filas = modeloTabla.getRowCount();

        for (int i = 0; i < filas; i++) {
            TareaDTO tarea = new TareaDTO();

            tarea.setIdTarea((String) modeloTabla.getValueAt(i, 0));
            tarea.setDescripcion((String) modeloTabla.getValueAt(i, 1));
            tarea.setVehiculoModelo((String) modeloTabla.getValueAt(i, 2));
            tarea.setIdOrden((String) modeloTabla.getValueAt(i, 3));
            tarea.setEstado((String) modeloTabla.getValueAt(i, 4));

            lista.add(tarea);
        }

        return lista;
    }

    private void configurarModeloTabla() {
        String[] columnas = {"ID", "Descripción", "Vehículo", "Orden", "Estado"};

        modeloTabla = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        jTable1.setModel(modeloTabla);

        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
    }

    private void estilizarTabla() {
        creacion.aplicarEstiloTabla(jScrollPane1, jTable1);
    }

    private void cargarHistorial() {
        modeloTabla.setRowCount(0);

        if (mecanicoActual == null) {
            mensajes.mostrarError(this,
                    "No se encontró información del mecánico.");

            return;
        }

        List<TareaDTO> lista = controlTareas.obtenerTareasCompletadasPorMecanico(
                mecanicoActual.getId_empleado()
        );

        for (TareaDTO t : lista) {
            modeloTabla.addRow(new Object[]{
                t.getIdTarea(),
                t.getDescripcion(),
                t.getVehiculoModelo(),
                t.getIdOrden(),
                t.getEstado()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAtras = new javax.swing.JButton();
        btnImprimirReporte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setMaximumSize(new java.awt.Dimension(32767, 32768));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 80));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 470, 210));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonRegresar.png"))); // NOI18N
        btnAtras.setContentAreaFilled(false);
        btnAtras.setDefaultCapable(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        btnImprimirReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnImprimirReporte.png"))); // NOI18N
        btnImprimirReporte.setBorderPainted(false);
        btnImprimirReporte.setContentAreaFilled(false);
        btnImprimirReporte.setDefaultCapable(false);
        btnImprimirReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirReporteActionPerformed(evt);
            }
        });
        jPanel1.add(btnImprimirReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PantallaHistorial.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        navegacion.mostrarMenuPrincipal();
        this.dispose();    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnImprimirReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirReporteActionPerformed

        List<TareaDTO> tareas = obtenerTareasDeLaTabla();

        if (tareas.isEmpty()) {
            mensajes.mostrarError(this, "No hay tareas para imprimir.");
            return;
        }
        String nombre = mecanicoActual != null ? mecanicoActual.getNombre() : "Mecánico";
        controlDocumentos.imprimirReporteTareasCompletadas(tareas, nombre);
    }//GEN-LAST:event_btnImprimirReporteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnImprimirReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
