/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import presentacion.controles.IControlOrdenes;
import presentacion.controles.IControlNavegacion;
import presentacion.validaciones.ValidacionException;

/**
 *
 * @author Abraham Coronel
 */
public class IniciarSesion extends javax.swing.JFrame {

    private final IControlOrdenes control;
    private final IControlNavegacion navegacion;

    public IniciarSesion(IControlOrdenes control, IControlNavegacion navegacion) {
        this.control = control;
        this.navegacion = navegacion;
        initComponents();
        configurarVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        correoText = new javax.swing.JTextField();
        contraseniaText = new javax.swing.JTextField();
        btnIniciarSesion = new javax.swing.JButton();
        jLabel_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        correoText.setForeground(new java.awt.Color(51, 51, 51));
        correoText.setText("correo...");
        correoText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                correoTextMouseClicked(evt);
            }
        });
        correoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoTextActionPerformed(evt);
            }
        });
        getContentPane().add(correoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 220, 40));

        contraseniaText.setForeground(new java.awt.Color(51, 51, 51));
        contraseniaText.setText("contraseña...");
        contraseniaText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contraseniaTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contraseniaTextMouseEntered(evt);
            }
        });
        contraseniaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseniaTextActionPerformed(evt);
            }
        });
        getContentPane().add(contraseniaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 220, 40));

        btnIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonIniciarSesion.png"))); // NOI18N
        btnIniciarSesion.setBorderPainted(false);
        btnIniciarSesion.setContentAreaFilled(false);
        btnIniciarSesion.setFocusPainted(false);
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 80, 20));

        jLabel_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IniciarSesion.png"))); // NOI18N
        jLabel_Fondo.setText("F");
        getContentPane().add(jLabel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 960, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarVentana() {
        this.setLocationRelativeTo(null);
    }

    private Boolean validarCampos() {
        String usuario = correoText.getText();
        String contra = contraseniaText.getText();

        try {
            control.validarCampoVacio(usuario, "Correo");
            control.validarCampoVacio(contra, "Contraseña");
        } catch (ValidacionException ex) {
            control.mostrarErrorCampos(ex.getMessage());
            return false;
        }
        return true;
    }

    private void iniciarSesion() {
        if (validarCampos()) {
            String usuario = correoText.getText();
            String contra = contraseniaText.getText();

            if (control.autenticarUsuario(usuario, contra)) {
                this.navegar();
            } else {
                control.mostrarErrorCampos("Usuario o contraseña incorrectos");
            }
        }
    }

    private void navegar() {
        navegacion.mostrarMenuPrincipal();
        this.dispose();
    }


    private void correoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoTextActionPerformed

    }//GEN-LAST:event_correoTextActionPerformed

    private void contraseniaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseniaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseniaTextActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        iniciarSesion();
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void correoTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correoTextMouseClicked
        if (correoText.getText().equals("correo...")) {
            correoText.setText("");
        }
    }//GEN-LAST:event_correoTextMouseClicked

    private void contraseniaTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseniaTextMouseEntered
        //nada que ver aqui, ya no lo pude borrar
    }//GEN-LAST:event_contraseniaTextMouseEntered

    private void contraseniaTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseniaTextMouseClicked
        if (contraseniaText.getText().equals("contraseña...")) {
            contraseniaText.setText("");
        }
    }//GEN-LAST:event_contraseniaTextMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JTextField contraseniaText;
    private javax.swing.JTextField correoText;
    private javax.swing.JLabel jLabel_Fondo;
    // End of variables declaration//GEN-END:variables
}
