/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import presentacion.controles.IControlNavegacion;

/**
 *
 * @author Abraham Coronel
 */
public class MenuPrincipalAdmin extends javax.swing.JFrame {

    private final IControlNavegacion navegacion;

    public MenuPrincipalAdmin(IControlNavegacion navegacion) {
        this.navegacion = navegacion;
        initComponents();
        configurarVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearOrden = new javax.swing.JButton();
        generarPresupuesto = new javax.swing.JButton();
        pagarOrden = new javax.swing.JButton();
        auditarCitaCliente = new javax.swing.JButton();
        reclamarGarantia = new javax.swing.JButton();
        asignarTarea = new javax.swing.JButton();
        venderRefacciones = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/4.png"))); // NOI18N
        crearOrden.setContentAreaFilled(false);
        crearOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(crearOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        generarPresupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5.png"))); // NOI18N
        generarPresupuesto.setContentAreaFilled(false);
        generarPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarPresupuestoActionPerformed(evt);
            }
        });
        getContentPane().add(generarPresupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        pagarOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/6.png"))); // NOI18N
        pagarOrden.setContentAreaFilled(false);
        pagarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(pagarOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        auditarCitaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/7.png"))); // NOI18N
        auditarCitaCliente.setContentAreaFilled(false);
        auditarCitaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auditarCitaClienteActionPerformed(evt);
            }
        });
        getContentPane().add(auditarCitaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, -1, -1));

        reclamarGarantia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/8.png"))); // NOI18N
        reclamarGarantia.setContentAreaFilled(false);
        getContentPane().add(reclamarGarantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, 120));

        asignarTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/asignar tarea.png"))); // NOI18N
        asignarTarea.setContentAreaFilled(false);
        asignarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarTareaActionPerformed(evt);
            }
        });
        getContentPane().add(asignarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        venderRefacciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/10.png"))); // NOI18N
        venderRefacciones.setContentAreaFilled(false);
        venderRefacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderRefaccionesActionPerformed(evt);
            }
        });
        getContentPane().add(venderRefacciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/11.png"))); // NOI18N
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, -1, -1));

        jLabel1_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuMecanico.png"))); // NOI18N
        getContentPane().add(jLabel1_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarVentana() {
        this.setLocationRelativeTo(null);
    }

    private void navegarClientesRegistrados() {
        navegacion.mostrarClientesRegistrados();
        this.dispose();
    }

    private void navegarOrdenesPendientes() {
        navegacion.mostrarOrdenesPendientes();
        this.dispose();
    }


    private void crearOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearOrdenActionPerformed
        this.navegarClientesRegistrados();
    }//GEN-LAST:event_crearOrdenActionPerformed

    private void pagarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarOrdenActionPerformed
        this.navegarOrdenesPendientes();
    }//GEN-LAST:event_pagarOrdenActionPerformed

    private void auditarCitaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auditarCitaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_auditarCitaClienteActionPerformed

    private void venderRefaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderRefaccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_venderRefaccionesActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void asignarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarTareaActionPerformed
        navegacion.mostrarPantallaElegirMecanico();
        this.dispose();
    }//GEN-LAST:event_asignarTareaActionPerformed

    private void generarPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarPresupuestoActionPerformed
        navegacion.mostrarPantallaSeleccionarCliente();
    }//GEN-LAST:event_generarPresupuestoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asignarTarea;
    private javax.swing.JButton auditarCitaCliente;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton crearOrden;
    private javax.swing.JButton generarPresupuesto;
    private javax.swing.JLabel jLabel1_fondo;
    private javax.swing.JButton pagarOrden;
    private javax.swing.JButton reclamarGarantia;
    private javax.swing.JButton venderRefacciones;
    // End of variables declaration//GEN-END:variables
}
