/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dto.OrdenDTO;
import presentacion.controles.IControlClientes;
import presentacion.controles.IControlCreacionUI;
import presentacion.controles.IControlMensajes;
import presentacion.controles.IControlNavegacion;
import presentacion.controles.IControlOrdenes;
import presentacion.controles.IControlPresupuestos;
import presentacion.controles.IControlRefacciones;
import presentacion.controles.IControlValidaciones;
import presentacion.controles.IControlVentas;

/**
 *
 * @author Abraham Coronel
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private final IControlNavegacion navegacion;
    private final IControlRefacciones controlRefacciones;
    private final IControlCreacionUI creacion;
    private final IControlMensajes mensajes;
    private final IControlVentas controlVentas;
    private final IControlValidaciones validaciones;
    private final IControlClientes clientes;
    private final IControlPresupuestos control;
    private final IControlOrdenes controlOrdenes;
    private final IControlPresupuestos presupuesto;
    private OrdenDTO orden;
    
    public MenuPrincipal(IControlNavegacion navegacion,IControlRefacciones controlRefacciones, IControlCreacionUI creacion, 
            IControlMensajes mensajes, IControlVentas controlVentas, IControlValidaciones validaciones, IControlClientes clientes, IControlPresupuestos control, IControlOrdenes controlOrdenes, IControlPresupuestos presupuesto) {
        this.navegacion = navegacion;
        this.controlRefacciones=controlRefacciones;
        this.creacion=creacion;
        this.mensajes=mensajes;
        this.controlVentas=controlVentas;
        this.validaciones=validaciones;
        this.clientes=clientes;
        this.control=control;
        this.controlOrdenes=controlOrdenes;
        this.presupuesto=presupuesto;
           
        initComponents();
        configurarVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearOrden = new javax.swing.JButton();
        generarPresupuesto = new javax.swing.JButton();
        pagarOrden = new javax.swing.JButton();
        verHistorial = new javax.swing.JButton();
        reclamarGarantia = new javax.swing.JButton();
        visualizarTarea = new javax.swing.JButton();
        venderRefacciones = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/4.png"))); // NOI18N
        crearOrden.setBorderPainted(false);
        crearOrden.setContentAreaFilled(false);
        crearOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(crearOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        generarPresupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5.png"))); // NOI18N
        generarPresupuesto.setBorderPainted(false);
        generarPresupuesto.setContentAreaFilled(false);
        generarPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarPresupuestoActionPerformed(evt);
            }
        });
        getContentPane().add(generarPresupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        pagarOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/6.png"))); // NOI18N
        pagarOrden.setBorderPainted(false);
        pagarOrden.setContentAreaFilled(false);
        pagarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(pagarOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        verHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnVerHistorial.png"))); // NOI18N
        verHistorial.setBorderPainted(false);
        verHistorial.setContentAreaFilled(false);
        verHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verHistorialActionPerformed(evt);
            }
        });
        getContentPane().add(verHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, -1, -1));

        reclamarGarantia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/8.png"))); // NOI18N
        reclamarGarantia.setBorderPainted(false);
        reclamarGarantia.setContentAreaFilled(false);
        getContentPane().add(reclamarGarantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, 120));

        visualizarTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/9.png"))); // NOI18N
        visualizarTarea.setBorderPainted(false);
        visualizarTarea.setContentAreaFilled(false);
        visualizarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarTareaActionPerformed(evt);
            }
        });
        getContentPane().add(visualizarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        venderRefacciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/10.png"))); // NOI18N
        venderRefacciones.setBorderPainted(false);
        venderRefacciones.setContentAreaFilled(false);
        venderRefacciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                venderRefaccionesMouseClicked(evt);
            }
        });
        venderRefacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderRefaccionesActionPerformed(evt);
            }
        });
        getContentPane().add(venderRefacciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/11.png"))); // NOI18N
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, -1, -1));

        jLabel1_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuMecanico.png"))); // NOI18N
        getContentPane().add(jLabel1_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarVentana() {
        this.setLocationRelativeTo(null);
    }

    private void navegarClientesRegistrados() {
        navegacion.mostrarClientesRegistrados();
        this.dispose();
    }

    private void navegarOrdenesPendientes() {
        navegacion.mostrarOrdenesPendientes();
        this.dispose();
    }

    private void navegarTareasMecanico() {
        navegacion.mostrarTareasMecanico();
        this.dispose();
    }

    private void navegarSeleccionarCliente() {
        navegacion.mostrarPantallaSeleccionarCliente(navegacion, clientes, creacion, control, controlOrdenes, presupuesto, orden, mensajes);
        this.dispose();
    }
    
    private void navegarVenderRefacciones(){
        navegacion.mostrarPantallaSeleccionarRefacciones(controlRefacciones, creacion, mensajes, navegacion, controlVentas, validaciones);
        this.dispose();
    }

    private void crearOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearOrdenActionPerformed
        this.navegarClientesRegistrados();
    }//GEN-LAST:event_crearOrdenActionPerformed

    private void pagarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarOrdenActionPerformed
        this.navegarOrdenesPendientes();
    }//GEN-LAST:event_pagarOrdenActionPerformed

    private void verHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verHistorialActionPerformed
        navegacion.mostrarPantallaHistorialTareas();
        this.dispose();
    }//GEN-LAST:event_verHistorialActionPerformed

    private void venderRefaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderRefaccionesActionPerformed
       
    }//GEN-LAST:event_venderRefaccionesActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void visualizarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarTareaActionPerformed
        this.navegarTareasMecanico();
    }//GEN-LAST:event_visualizarTareaActionPerformed

    private void generarPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarPresupuestoActionPerformed
        this.navegarSeleccionarCliente();
    }//GEN-LAST:event_generarPresupuestoActionPerformed

    private void venderRefaccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_venderRefaccionesMouseClicked
        this.navegarVenderRefacciones();
        this.dispose();
    }//GEN-LAST:event_venderRefaccionesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton crearOrden;
    private javax.swing.JButton generarPresupuesto;
    private javax.swing.JLabel jLabel1_fondo;
    private javax.swing.JButton pagarOrden;
    private javax.swing.JButton reclamarGarantia;
    private javax.swing.JButton venderRefacciones;
    private javax.swing.JButton verHistorial;
    private javax.swing.JButton visualizarTarea;
    // End of variables declaration//GEN-END:variables
}
