/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dto.OrdenDTO;
import java.time.LocalDate;
import presentacion.validaciones.ValidacionException;

/**
 *
 * @author Abraham Coronel
 */
public class PantallaDatosOrden extends javax.swing.JFrame {

    private final IControlOrdenes control = ControlOrdenes.getInstancia();
    private OrdenDTO orden;

    /**
     * Creates new form PantallaCrearOrden
     */
    public PantallaDatosOrden() {
        initComponents();
    }

    public PantallaDatosOrden(OrdenDTO orden) {
        initComponents();
        this.orden = orden;
        configurarVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        txtaFallaReportada = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaServiciosSolicitados = new javax.swing.JTextArea();
        dtFechaIngreso = new com.github.lgooddatepicker.components.DatePicker();
        btnRegresar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        txtFallaReportada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtaFallaReportada.setColumns(20);
        txtaFallaReportada.setRows(5);
        jScrollPane3.setViewportView(txtaFallaReportada);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 280, 110));

        txtaServiciosSolicitados.setColumns(20);
        txtaServiciosSolicitados.setRows(5);
        jScrollPane2.setViewportView(txtaServiciosSolicitados);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 280, 110));
        getContentPane().add(dtFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 250, 40));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonRegresar.png"))); // NOI18N
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonAceptar.png"))); // NOI18N
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, -1, -1));

        txtFallaReportada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datosSolicitados.png"))); // NOI18N
        getContentPane().add(txtFallaReportada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarVentana() {
        this.setLocationRelativeTo(null);
    }

    private void guardarDatosOrden() {
        LocalDate fecha = dtFechaIngreso.getDate();
        String falla = txtaFallaReportada.getText();
        String servicios = txtaServiciosSolicitados.getText();

        this.orden.setFechaIngreso(fecha);
        this.orden.setFallaReportada(falla);
        this.orden.setServicioSolicitado(servicios);

    }

    private Boolean validarCampos() {
        try {
            control.validarObjetoNull(dtFechaIngreso.getDate(), "Fecha de ingreso");
            control.validarCampoVacio(txtaFallaReportada.getText(), "Falla reportada");
            control.validarCampoVacio(txtaServiciosSolicitados.getText(), "Servicios Solicitados");
            return true;
        } catch (ValidacionException ex) {
            control.mostrarErrorCampos(ex.getMessage());
            return false;
        }
    }


    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        control.mostrarMenuPrincipal();
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (validarCampos()) {
            guardarDatosOrden();
            control.crearOrden(orden);
            control.mostrarMenuPrincipal();
            this.dispose();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnRegresar;
    private com.github.lgooddatepicker.components.DatePicker dtFechaIngreso;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel txtFallaReportada;
    private javax.swing.JTextArea txtaFallaReportada;
    private javax.swing.JTextArea txtaServiciosSolicitados;
    // End of variables declaration//GEN-END:variables
}
