/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dto.OrdenDTO;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author Abraham Coronel
 */
public class PantallaDatosOrden extends javax.swing.JFrame {

    private final IControlOrdenes control = ControlOrdenes.getInstancia();
    private OrdenDTO orden;

    /**
     * Creates new form PantallaCrearOrden
     */
    public PantallaDatosOrden() {
        initComponents();
    }

    public PantallaDatosOrden(OrdenDTO orden) {
        initComponents();
        this.orden = orden;
        configurarVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAtras = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaServiciosSolicitados = new javax.swing.JTextArea();
        lblSiguiente = new javax.swing.JLabel();
        dtFechaIngreso = new com.github.lgooddatepicker.components.DatePicker();
        txtFallaReportada = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAtras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAtras.setText("      <");
        lblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(lblAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 70, 50));

        txtaServiciosSolicitados.setColumns(20);
        txtaServiciosSolicitados.setRows(5);
        jScrollPane2.setViewportView(txtaServiciosSolicitados);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 280, 110));

        lblSiguiente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSiguiente.setText("         >");
        lblSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSiguienteMouseClicked(evt);
            }
        });
        getContentPane().add(lblSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 90, 50));
        getContentPane().add(dtFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 250, 40));

        txtFallaReportada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datosSolicitados.png"))); // NOI18N
        getContentPane().add(txtFallaReportada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarVentana() {
        this.setLocationRelativeTo(null);
    }

    private boolean guardarDatosOrden() {
        LocalDate fecha = dtFechaIngreso.getDate();
        String falla = txtFallaReportada.getText();
        String servicios = txtaServiciosSolicitados.getText();


        this.orden.setFechaIngreso(fecha);
        this.orden.setFallaReportada(falla);
        this.orden.setServicioSolicitado(servicios);

        return true;

    }


    private void lblSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSiguienteMouseClicked
        if (guardarDatosOrden()) {
            try {
                control.crear0rden(this.orden);

                JOptionPane.showMessageDialog(this, new PantallaConfirmacion(), "Orden creada exitosamente", JOptionPane.PLAIN_MESSAGE);

                control.mostrarMenuPrincipal();
                this.dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al guardar la orden: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_lblSiguienteMouseClicked

    private void lblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseClicked
        control.mostrarMenuPrincipal();
        this.dispose();
    }//GEN-LAST:event_lblAtrasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DatePicker dtFechaIngreso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblAtras;
    private javax.swing.JLabel lblSiguiente;
    private javax.swing.JLabel txtFallaReportada;
    private javax.swing.JTextArea txtaServiciosSolicitados;
    // End of variables declaration//GEN-END:variables
}
