/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dto.OrdenDTO;
import dto.VehiculoDTO;

/**
 *
 * @author PC Gamer
 */
public class PantallaDatosVehiculo extends javax.swing.JFrame {

    private final IControlOrdenes control = ControlOrdenes.getInstancia();
    private OrdenDTO orden;
    
    public PantallaDatosVehiculo() {
        initComponents();
    }
    
    public PantallaDatosVehiculo(OrdenDTO orden) {
        initComponents();
        this.orden = orden;
        configurarVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtColor = new javax.swing.JTextField();
        lblAtras = new javax.swing.JLabel();
        lblSiguiente = new javax.swing.JLabel();
        txtKilometraje = new javax.swing.JTextField();
        txtPlacas = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        cbModelo = new javax.swing.JComboBox<>();
        cbMarca = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtColor.setBackground(new java.awt.Color(255, 255, 255));
        txtColor.setForeground(new java.awt.Color(0, 0, 0));
        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });
        getContentPane().add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 220, -1));

        lblAtras.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblAtras.setText("   <");
        lblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(lblAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 60, 60));

        lblSiguiente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSiguiente.setText("    >");
        lblSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSiguienteMouseClicked(evt);
            }
        });
        getContentPane().add(lblSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 470, 70, 50));

        txtKilometraje.setBackground(new java.awt.Color(255, 255, 255));
        txtKilometraje.setForeground(new java.awt.Color(0, 0, 0));
        txtKilometraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKilometrajeActionPerformed(evt);
            }
        });
        getContentPane().add(txtKilometraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 220, -1));

        txtPlacas.setBackground(new java.awt.Color(255, 255, 255));
        txtPlacas.setForeground(new java.awt.Color(0, 0, 0));
        txtPlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacasActionPerformed(evt);
            }
        });
        getContentPane().add(txtPlacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 220, -1));

        txtAnio.setBackground(new java.awt.Color(255, 255, 255));
        txtAnio.setForeground(new java.awt.Color(0, 0, 0));
        txtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioActionPerformed(evt);
            }
        });
        getContentPane().add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 220, -1));

        cbModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Corolla", "RAV4", "Yaris", "Fiesta" }));
        cbModelo.setBackground(new java.awt.Color(255, 255, 255));
        cbModelo.setForeground(new java.awt.Color(0, 0, 0));
        cbModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbModeloActionPerformed(evt);
            }
        });
        getContentPane().add(cbModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 220, -1));

        cbMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toyota", "Nissan", "Kia", "Tesla" }));
        cbMarca.setBackground(new java.awt.Color(255, 255, 255));
        cbMarca.setForeground(new java.awt.Color(0, 0, 0));
        cbMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(cbMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 220, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datosAuto.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarVentana() {
        this.setLocationRelativeTo(null);
    }
    
    private boolean guardarDatosVehiculo() {
        String marca = (String) cbMarca.getSelectedItem();
        String modelo = (String) cbModelo.getSelectedItem();
        String anio = txtAnio.getText();
        String placas = txtPlacas.getText();
        String km = txtKilometraje.getText();
        String color = txtColor.getText();

        VehiculoDTO vehiculo = new VehiculoDTO(marca, modelo, anio, placas, km, color);

        this.orden.setVehiculo(vehiculo);

        return true;

    }
    
    private void txtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioActionPerformed

    private void txtPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacasActionPerformed

    private void txtKilometrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKilometrajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKilometrajeActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void cbMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMarcaActionPerformed

    private void cbModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbModeloActionPerformed

    private void lblSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSiguienteMouseClicked
        if (guardarDatosVehiculo()) {
            control.mostrarDatosOrden(this.orden);
            this.dispose();
        }
    }//GEN-LAST:event_lblSiguienteMouseClicked

    private void lblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseClicked
        control.mostrarMenuPrincipal();
        this.dispose();
    }//GEN-LAST:event_lblAtrasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbMarca;
    private javax.swing.JComboBox<String> cbModelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAtras;
    private javax.swing.JLabel lblSiguiente;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtKilometraje;
    private javax.swing.JTextField txtPlacas;
    // End of variables declaration//GEN-END:variables
}
