/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import presentacion.controles.IControlOrdenes;
import dto.ClienteDTO;
import dto.OrdenDTO;
import dto.enums.NavegacionOrigen;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import presentacion.controles.IControlClientes;
import presentacion.controles.IControlCreacionUI;
import presentacion.controles.IControlNavegacion;

/**
 *
 * @author payde
 */
public class PantallaClientesRegistrados extends javax.swing.JFrame {

    private final IControlOrdenes control;
    private final IControlClientes clientes;
    private final IControlNavegacion navegacion;
    private final IControlCreacionUI creacion;

    public PantallaClientesRegistrados(IControlOrdenes control, IControlNavegacion navegacion, IControlClientes clientes, IControlCreacionUI creacion) {
        this.control = control;
        this.navegacion = navegacion;
        this.clientes = clientes;
        this.creacion = creacion;
        initComponents();
        configurarVentana();
        generarListaClientes();
    }

    private void configurarVentana() {
        this.setLocationRelativeTo(null);
        scrollPaneClientes.setOpaque(false);
        scrollPaneClientes.getViewport().setOpaque(false);
        scrollPaneClientes.setBorder(null);
    }

    private void generarListaClientes() {
        List<ClienteDTO> listaClientes = clientes.obtenerClientesMock();

        JPanel contenedor = new JPanel();
        contenedor.setLayout(new BoxLayout(contenedor, BoxLayout.Y_AXIS));
        contenedor.setOpaque(false);

        for (ClienteDTO cliente : listaClientes) {
            String texto = cliente.getNombre() + " " + cliente.getApellidoP() + " "
                    + cliente.getApellidoM() + " | " + cliente.getTelefono();
            JPanel panel = creacion.crearPanelCliente(texto);
            panel.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    // 3. Al hacer clic, llamamos al método privado de esta clase
                    clienteSeleccionado(cliente);
                }
            });

            contenedor.add(panel);
        }

        scrollPaneClientes.setViewportView(contenedor);
    }

    private void clienteSeleccionado(ClienteDTO cliente) {
        OrdenDTO ordenNueva = control.crearOrdenConCliente(cliente);
        navegacion.mostrarVehiculosRegistrados(ordenNueva, NavegacionOrigen.CLIENTES_REGISTRADOS);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        scrollPaneClientes = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(410, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonAgregar_1.png"))); // NOI18N
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonRegresar.png"))); // NOI18N
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 50, 50));

        scrollPaneClientes.setBackground(new java.awt.Color(242, 242, 242));
        getContentPane().add(scrollPaneClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 280, 310));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pantallaClientesRegistrados.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 270));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 270));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 270));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        navegacion.mostrarDatosCliente();
        this.dispose();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        navegacion.mostrarMenuPrincipal();
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane scrollPaneClientes;
    // End of variables declaration//GEN-END:variables
}
