/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dto.OrdenDTO;
import dto.VehiculoDTO;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import presentacion.controles.IControlNavegacion;
import presentacion.controles.IControlOrdenes;
import presentacion.enums.NavegacionOrigen;

public class PantallaVehiculosRegistrados extends javax.swing.JFrame {

    private final IControlOrdenes control;
    private final IControlNavegacion navegacion;
    private final OrdenDTO orden;
    private final NavegacionOrigen origen;

    public PantallaVehiculosRegistrados(IControlOrdenes control, IControlNavegacion navegacion, OrdenDTO orden, NavegacionOrigen origen) {
        initComponents();
        this.control = control;
        this.navegacion = navegacion;
        this.orden = orden;
        this.origen = origen;
        configurarVentana();
        generarListaVehiculos();
    }

    private void configurarVentana() {
        this.setLocationRelativeTo(null);
        scrollPaneVehiculos.setOpaque(false);
        scrollPaneVehiculos.getViewport().setOpaque(false);
        scrollPaneVehiculos.setBorder(null);
    }

    private void generarListaVehiculos() {
        List<VehiculoDTO> listaVehiculo = control.obtenerVehiculosMock();

        JPanel contenedor = new JPanel();
        contenedor.setLayout(new BoxLayout(contenedor, BoxLayout.Y_AXIS));
        contenedor.setOpaque(false);

        for (VehiculoDTO vehiculo : listaVehiculo) {
            String texto = vehiculo.getMarca() + " " + vehiculo.getModelo() + " | "
                    + vehiculo.getPlacas();
            JPanel panel = control.crearPanelVehiculo(texto);
            panel.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    vehiculoSeleccionado(vehiculo);
                }
            });

            contenedor.add(panel);
        }

        scrollPaneVehiculos.setViewportView(contenedor);
    }

    private void vehiculoSeleccionado(VehiculoDTO vehiculo) {
        this.orden.setVehiculo(vehiculo);
        navegacion.mostrarDatosOrden(this.orden, NavegacionOrigen.VEHICULOS_REGISTRADOS, this.origen);
        this.dispose();
    }

    private void regresar() {
        navegacion.regresarVehiculosRegistrados(this.origen);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        scrollPaneVehiculos = new javax.swing.JScrollPane();
        jLabel1_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(410, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonRegresar.png"))); // NOI18N
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, 50));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonAgregar_1.png"))); // NOI18N
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        scrollPaneVehiculos.setBackground(new java.awt.Color(242, 242, 242));
        getContentPane().add(scrollPaneVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 290, 300));

        jLabel1_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pantallaVehiculosRegistrados.png"))); // NOI18N
        getContentPane().add(jLabel1_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        regresar();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        navegacion.mostrarDatosVehiculo(this.orden, NavegacionOrigen.DATOS_VEHICULO);
        this.dispose();
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1_fondo;
    private javax.swing.JScrollPane scrollPaneVehiculos;
    // End of variables declaration//GEN-END:variables
}
