/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.ComprarRefaccion;

import dto.RefaccionDTO;
import dto.RespuestaPagoDTO;
import dto.SolicitudPagoDTO;
import dto.VentaDTO;
import dto.VentaRefaccionDTO;
import dto.enums.MetodoPago;
import gestionPagos.GestorPagos;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import presentacion.controles.IControlMensajes;
import presentacion.controles.IControlNavegacion;
import presentacion.controles.IControlRefacciones;
import presentacion.controles.IControlValidaciones;
import presentacion.controles.IControlVentas;
import presentacion.validaciones.ValidacionException;

/**
 *
 * @author Pride Factor Black
 */
public class PantallaPagoTarjeta extends javax.swing.JFrame {
    private List<RefaccionDTO> listaCompra;
    private double total;
    private IControlMensajes mensajes;
    private IControlNavegacion navegacion;
    private IControlRefacciones controlRefacciones;
    private IControlVentas controlVentas;
    private IControlValidaciones validaciones;
    
    /**
     * Creates new form PantallaPagoTarjeta
     */
    public PantallaPagoTarjeta(List<RefaccionDTO> lista, double total, IControlNavegacion navegacion, IControlMensajes mensajes, IControlRefacciones controlRefacciones, 
                               IControlVentas controlVentas, IControlValidaciones validaciones) {
        initComponents();
        this.listaCompra = lista;
        this.total = total;
        this.navegacion = navegacion;
        this.mensajes = mensajes;
        this.controlRefacciones = controlRefacciones;
        this.controlVentas = controlVentas;
        this.validaciones = validaciones;
    }

    private void finalizarVenta(String idTransaccion) {
        try {
            for (RefaccionDTO itemCarrito : this.listaCompra) {
                RefaccionDTO refaccionEnBD = controlRefacciones.buscarRefaccionPorId(itemCarrito.getId_refaccion());

                if (refaccionEnBD != null) {
                    int cantidadComprada = itemCarrito.getStock();
                    int nuevoStock = refaccionEnBD.getStock() - cantidadComprada;

                    refaccionEnBD.setStock(nuevoStock);
                    controlRefacciones.actualizarRefaccion(refaccionEnBD);
                }
            }

            List<VentaRefaccionDTO> detallesVenta = new ArrayList<>();
            for (RefaccionDTO item : this.listaCompra) {
                VentaRefaccionDTO detalle = new VentaRefaccionDTO();
                detalle.setId_refaccion(item.getId_refaccion());
                detalle.setCantidad(item.getStock());
                detalle.setPrecioUnitario(item.getPrecioUnitario());
                detallesVenta.add(detalle);
            }

            VentaDTO ventaRegistrada = controlVentas.crearVenta(detallesVenta);

            if (ventaRegistrada != null) {
                mensajes.mostrarExito("¡Compra Exitosa!\nID Pago: " + idTransaccion);
                navegacion.mostrarPantallaResumenRe(listaCompra, total, navegacion);
                this.dispose();
            } else {
                mensajes.mostrarError(this, "El pago pasó, pero no se pudo registrar la venta.");
            }

        } catch (Exception e) {
            e.printStackTrace();
            mensajes.mostrarError(this, "Error finalizando compra: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNmnTarjeta = new javax.swing.JTextField();
        txtCvv = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtNmnTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 160, 30));

        txtCvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCvvActionPerformed(evt);
            }
        });
        getContentPane().add(txtCvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 160, 30));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonCancelarPago.png"))); // NOI18N
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, 20));

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonAceptarPago.png"))); // NOI18N
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, 20));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PantallaTarjeta.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCvvActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
       String numero = txtNmnTarjeta.getText();
       String cvv = txtCvv.getText();

        try {
            validaciones.validarCampoVacio(numero, "Número de Tarjeta");
            validaciones.validarCampoVacio(cvv, "CVV");
            validaciones.validarCampoNumerico(numero, "Número de Tarjeta");
            validaciones.validarCampoNumerico(cvv, "CVV");
        } catch (ValidacionException ex) {
            mensajes.mostrarErrorCamposConPadre(this, ex.getMessage());
            return;
        }

        Map<String, String> datosPago = new HashMap<>();
        datosPago.put("numeroTarjeta", numero);
        datosPago.put("cvv", cvv);

        SolicitudPagoDTO solicitud = new SolicitudPagoDTO(
            this.total, 
            "ORD-" + System.currentTimeMillis(), 
            MetodoPago.TARJETA, 
            datosPago,
            true 
        );

        try {
            GestorPagos gestor = new GestorPagos();
            RespuestaPagoDTO respuesta = gestor.procesarPago(solicitud);

            if (respuesta.getExito()) {
                finalizarVenta(respuesta.getIdtransaccion());
            } else {
                mensajes.mostrarError(this, "Pago rechazado: " + respuesta.getMensaje());
            }
        } catch (Exception e) {
            mensajes.mostrarError(this, "Error técnico: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       navegacion.mostrarMenuPrincipal();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField txtCvv;
    private javax.swing.JTextField txtNmnTarjeta;
    // End of variables declaration//GEN-END:variables
}
