/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.ComprarRefaccion;

import dto.RefaccionDTO;
import java.awt.Color;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import presentacion.controles.IControlDocumentos;
import presentacion.controles.IControlMensajes;
import presentacion.controles.IControlNavegacion;



/**
 *
 * @author Pride Factor Black
 */
public class pantallaResumenRe extends javax.swing.JFrame {
    private List<RefaccionDTO> listaDeCompras; 
    private double totalPagar;
    private IControlNavegacion navegacion;
    private JTable tablaResumen;
    private DefaultTableModel modelo;
    private IControlDocumentos documentos;
    private IControlMensajes mensajes;
    /**
     * Creates new form pantallaResumen
     */
    public pantallaResumenRe(List<RefaccionDTO> productosSeleccionados, double total, IControlNavegacion navegacion, IControlDocumentos documentos, 
                             IControlMensajes mensajes) {
        this.listaDeCompras = productosSeleccionados;
        this.totalPagar = total;
        this.navegacion = navegacion;
        this.documentos = documentos;
        this.mensajes = mensajes;
        initComponents();
        
        configurarVentana();
        cargarDatosEnTabla();
    }
    
    private void configurarVentana() {
        this.setLocationRelativeTo(null);
        ScrollPaneResumen.setOpaque(false);
        ScrollPaneResumen.getViewport().setOpaque(false);
        ScrollPaneResumen.setBorder(null);
        ScrollPaneResumen.getViewport().setBorder(null);
    }

    private void cargarDatosEnTabla() {
        String[] columnas = {"Producto", "Cant.", "Precio", "Importe"};

        modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        if (this.listaDeCompras != null) {
            for (RefaccionDTO r : this.listaDeCompras) {        
                double importe = r.getPrecioUnitario() * r.getStock(); // Asumiendo stock = cantidad comprada

                Object[] fila = {
                    r.getNombre(),            
                    r.getStock(),              
                    String.format("$%.2f", r.getPrecioUnitario()), 
                    String.format("$%.2f", importe)              
                };
                modelo.addRow(fila);
            }
        }
        
        modelo.addRow(new Object[]{"", "", "", ""});
        modelo.addRow(new Object[]{"", "", "TOTAL:", String.format("$%.2f", this.totalPagar)});

        tablaResumen = new JTable(modelo);
        tablaResumen.setOpaque(false);
        tablaResumen.setBackground(new Color(0, 0, 0, 0)); 
        tablaResumen.setForeground(Color.WHITE);           
        tablaResumen.setShowGrid(false);                   
        tablaResumen.setRowHeight(25); 
        tablaResumen.setFillsViewportHeight(true);
        tablaResumen.getTableHeader().setReorderingAllowed(false); 
        
        tablaResumen.setSelectionBackground(new Color(255, 255, 255, 50));
        tablaResumen.setSelectionForeground(null);

        ScrollPaneResumen.setViewportView(tablaResumen);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPaneResumen = new javax.swing.JScrollPane();
        descargar = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(ScrollPaneResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 350, 280));

        descargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/download.png"))); // NOI18N
        descargar.setBorderPainted(false);
        descargar.setContentAreaFilled(false);
        descargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descargarActionPerformed(evt);
            }
        });
        getContentPane().add(descargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonRegresar.png"))); // NOI18N
        menu.setBorderPainted(false);
        menu.setContentAreaFilled(false);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/resumen.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        navegacion.mostrarMenuPrincipal();
        this.dispose();
    }//GEN-LAST:event_menuActionPerformed

    private void descargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descargarActionPerformed
        if (documentos == null || mensajes == null) {
            System.err.println("Error: Controles nulos en pantallaResumenRe");
            return;
        }
        String correoDestino = mensajes.solicitarDato("Ingrese el correo electrónico para enviar el resumen:", "Enviar Resumen", "");
        
        if (correoDestino == null || correoDestino.trim().isEmpty()) {
            return;
        }

        this.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR));
        
        new Thread(() -> {
            try {
                documentos.enviarCompraPorCorreo(listaDeCompras, totalPagar, correoDestino.trim());
                
                javax.swing.SwingUtilities.invokeLater(() -> {
                    this.setCursor(java.awt.Cursor.getDefaultCursor());
                    mensajes.mostrarExito("El resumen se ha enviado correctamente a: " + correoDestino);
                });
                
            } catch (Exception e) {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    this.setCursor(java.awt.Cursor.getDefaultCursor());
                    mensajes.mostrarError(this, "No se pudo enviar el correo: " + e.getMessage());
                });
            }
        }).start();
    }//GEN-LAST:event_descargarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPaneResumen;
    private javax.swing.JButton descargar;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JButton menu;
    // End of variables declaration//GEN-END:variables
}
