/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.ComprarRefaccion;

import dto.RefaccionDTO;
import dto.RespuestaPagoDTO;
import dto.SolicitudPagoDTO;
import dto.VentaDTO;
import dto.VentaRefaccionDTO;
import dto.enums.MetodoPago;
import gestionPagos.GestorPagos;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import presentacion.controles.IControlDocumentos;
import presentacion.controles.IControlMensajes;
import presentacion.controles.IControlNavegacion;
import presentacion.controles.IControlRefacciones;
import presentacion.controles.IControlValidaciones;
import presentacion.controles.IControlVentas;
import presentacion.validaciones.ValidacionException;

/**
 *
 * @author Pride Factor Black
 */
public class PantallaPagoPayPal extends javax.swing.JFrame {
    private List<RefaccionDTO> listaCompra;
    private double total;
    private IControlMensajes mensajes;
    private IControlNavegacion navegacion;
    private IControlRefacciones controlRefacciones;
    private IControlVentas controlVentas;
    private IControlValidaciones validaciones;
    private IControlDocumentos documentos;
    /**
     * Creates new form PantallaPagoPayPal
     */
    public PantallaPagoPayPal(List<RefaccionDTO> lista, double total, IControlNavegacion navegacion, IControlMensajes mensajes, IControlRefacciones controlRefacciones, 
                               IControlVentas controlVentas, IControlValidaciones validaciones) {
        initComponents();
        this.listaCompra = lista;
        this.total = total;
        this.navegacion = navegacion;
        this.mensajes = mensajes;
        this.controlRefacciones = controlRefacciones;
        this.controlVentas = controlVentas;
        this.validaciones = validaciones;
    }

    private void finalizarVenta(String idTransaccion) {
        try {
            for (RefaccionDTO itemCarrito : this.listaCompra) {
                RefaccionDTO refaccionEnBD = controlRefacciones.buscarRefaccionPorId(itemCarrito.getId_refaccion());

                if (refaccionEnBD != null) {
                    int cantidadComprada = itemCarrito.getStock();
                    int nuevoStock = refaccionEnBD.getStock() - cantidadComprada;

                    refaccionEnBD.setStock(nuevoStock);
                    controlRefacciones.actualizarRefaccion(refaccionEnBD);
                }
            }

            List<VentaRefaccionDTO> detallesVenta = new ArrayList<>();

            for (RefaccionDTO item : this.listaCompra) {
                VentaRefaccionDTO detalle = new VentaRefaccionDTO();
                detalle.setId_refaccion(item.getId_refaccion());
                detalle.setCantidad(item.getStock());
                detalle.setPrecioUnitario(item.getPrecioUnitario());
                detallesVenta.add(detalle);
            }

            VentaDTO ventaRegistrada = controlVentas.crearVenta(detallesVenta);

            if (ventaRegistrada != null) {
                mensajes.mostrarExito("¡Compra Exitosa!\nID Pago: " + idTransaccion);
                navegacion.mostrarMenuPrincipal();
                this.dispose();
            } else {
                mensajes.mostrarError(this, "El pago pasó, pero no se pudo registrar la venta.");
            }

        } catch (Exception e) {
            e.printStackTrace();
            mensajes.mostrarError(this, "Error finalizando compra: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCorreoElectronico = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCorreoElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoElectronicoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 170, 30));

        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 170, 30));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonRegresar.png"))); // NOI18N
        btnRegresar.setContentAreaFilled(false);
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonCancelarPago.png"))); // NOI18N
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 80, 20));

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonAceptarPago.png"))); // NOI18N
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 80, 20));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PantallaPayPal.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoElectronicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoElectronicoActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       navegacion.mostrarMenuPrincipal();
       this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String correo = txtCorreoElectronico.getText();
        String pass = txtContraseña.getText();

        try {
            validaciones.validarCampoVacio(correo, "Correo Electrónico");
            validaciones.validarCampoVacio(pass, "Contraseña");
            validaciones.validarEmail(correo);
        } catch (ValidacionException ex) {
            mensajes.mostrarErrorCamposConPadre(this, ex.getMessage());
            return;
        }

        Map<String, String> datosPago = new HashMap<>();
        datosPago.put("correo", correo);
        datosPago.put("contrasena", pass);

        SolicitudPagoDTO solicitud = new SolicitudPagoDTO(
            this.total, 
            "ORD-" + System.currentTimeMillis(), 
            MetodoPago.PAYPAL, 
            datosPago,
            true 
        );

        try {
            GestorPagos gestor = new GestorPagos();
            RespuestaPagoDTO respuesta = gestor.procesarPago(solicitud);

            if (respuesta.getExito()) {
                finalizarVenta(respuesta.getIdtransaccion());
                navegacion.mostrarPantallaResumenRe(listaCompra, total, navegacion, documentos, mensajes);
            } else {
                mensajes.mostrarError(this, "PayPal rechazó el pago: " + respuesta.getMensaje());
            }
        } catch (Exception e) {
            mensajes.mostrarError(this, "Error técnico: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtCorreoElectronico;
    // End of variables declaration//GEN-END:variables
}
