/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.ComprarRefaccion;

import dto.RefaccionDTO;
import java.util.List;

/**
 *
 * @author Pride Factor Black
 */
public class PantallaPagoTarjeta extends javax.swing.JFrame {
    private List<RefaccionDTO> listaCompra;
    private double total;
    /**
     * Creates new form PantallaPagoTarjeta
     */
    public PantallaPagoTarjeta(List<RefaccionDTO> lista, double total) {
        initComponents();
        this.listaCompra = lista;
        this.total = total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNmnTarjeta = new javax.swing.JTextField();
        txtCvv = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtNmnTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 160, 30));

        txtCvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCvvActionPerformed(evt);
            }
        });
        getContentPane().add(txtCvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 160, 30));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonCancelarPago.png"))); // NOI18N
        btnCancelar.setContentAreaFilled(false);
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, 20));

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonAceptarPago.png"))); // NOI18N
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, 20));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PantallaTarjeta.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCvvActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
       String numero = txtNmnTarjeta.getText();
       String cvv = txtCvv.getText();
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField txtCvv;
    private javax.swing.JTextField txtNmnTarjeta;
    // End of variables declaration//GEN-END:variables
}
