/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.GenerarPresupuesto;
    
import dto.ClienteDTO;
import dto.OrdenDTO;
import dto.PresupuestoDTO;
import dto.ServicioDTO;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import presentacion.controles.IControlClientes;
import presentacion.controles.IControlCreacionUI;
import presentacion.controles.IControlMensajes;
import presentacion.controles.IControlNavegacion;
import presentacion.controles.IControlOrdenes;
import presentacion.controles.IControlPresupuestos;
import presentacion.controles.IControlRefacciones;
import presentacion.controles.IControlServicios;

/**
 *
 * @author Pride Factor Black
 */
public class PantallaSeleccionarOrden extends javax.swing.JFrame {
    private final IControlNavegacion navegacion;
    private final IControlOrdenes controlOrdenes; 
    private final IControlCreacionUI creacion;
    private final ClienteDTO clienteSeleccionado;
    private final OrdenDTO orden;
    private final PresupuestoDTO presupuesto;
    private final ServicioDTO servicio;
    private final IControlServicios controlServicios;
    private final IControlRefacciones controlRefacciones;
    private final IControlPresupuestos controlPresupuesto;
    private final IControlMensajes mensajes;
    private final IControlClientes clientes;
    /**
     * Creates new form PantallaPresupuestoGenerado
     */
    public PantallaSeleccionarOrden(IControlNavegacion navegacion, IControlOrdenes controlOrdenes, IControlCreacionUI creacion, ClienteDTO clienteSeleccionado,OrdenDTO orden, PresupuestoDTO presupuesto, ServicioDTO servicio, IControlServicios controlServicios, 
            IControlRefacciones controlRefacciones, IControlPresupuestos controlPresupuesto, IControlMensajes mensajes, IControlClientes clientes) {
        initComponents();
        configurarVentana();
        this.navegacion = navegacion;
        this.controlOrdenes = controlOrdenes;      
        this.creacion = creacion;
        this.clienteSeleccionado = clienteSeleccionado;
        this.orden = orden;
        this.presupuesto=presupuesto;
        this.servicio=servicio;
        this.controlServicios= controlServicios;
        this.controlRefacciones=controlRefacciones;
        this.controlPresupuesto=controlPresupuesto;
        this.mensajes=mensajes;
        this.clientes=clientes;
        
        scrollPaneOrdenes.setOpaque(false);
        scrollPaneOrdenes.getViewport().setOpaque(false);
        scrollPaneOrdenes.setBorder(null);
        scrollPaneOrdenes.getViewport().setBorder(null);
        
        generarListaOrdenes();
    }

   private void generarListaOrdenes() {
    List<OrdenDTO> ordenes = controlOrdenes.buscarOrdenesPorCliente(clienteSeleccionado);


    JPanel contenedor = new JPanel();
    contenedor.setLayout(new BoxLayout(contenedor, BoxLayout.Y_AXIS));
    contenedor.setOpaque(false);

    if (ordenes == null || ordenes.isEmpty()) {
        JPanel panelVacio = creacion.crearPanelInformativo("Este cliente no tiene órdenes registradas.", true);
        contenedor.add(panelVacio);

    } else {
        
        for (OrdenDTO o : ordenes) {

            String texto =
                    "Folio: " + o.getIdOrden() +
                    "  |  Falla: " + o.getFallaReportada();

            JPanel panelOrden = creacion.crearPanelOrden(texto);

            panelOrden.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            panelOrden.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    navegacion.mostrarPantallaGenerarPresupuesto(navegacion, creacion, o, clienteSeleccionado, presupuesto, servicio, controlServicios, controlRefacciones, controlPresupuesto, mensajes, clientes);
                    dispose();
                }
            });

            contenedor.add(panelOrden);
            contenedor.add(creacion.crearSeparador(8));
        }
    }
    scrollPaneOrdenes.setViewportView(contenedor);
}
  
     private void configurarVentana() {
         this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        scrollPaneOrdenes = new javax.swing.JScrollPane();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonRegresar.png"))); // NOI18N
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, 50));
        getContentPane().add(scrollPaneOrdenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 300, 260));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PantallaSeleccionarOrdenCUA.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        navegacion.mostrarPantallaSeleccionarCliente(navegacion, clientes, creacion, controlPresupuesto, controlOrdenes, controlPresupuesto, orden, mensajes);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JScrollPane scrollPaneOrdenes;
    // End of variables declaration//GEN-END:variables
}
