/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.GenerarPresupuesto;
import dto.OrdenDTO;
import presentacion.controles.IControlClientes;
import presentacion.controles.IControlCreacionUI;
import presentacion.controles.IControlNavegacion;
import presentacion.controles.IControlOrdenes;
/**
 *
 * @author Pride Factor Black
 */
public class PantallaGenerarPresupuesto extends javax.swing.JFrame {
    private final IControlNavegacion navegacion;
    private final IControlOrdenes orden;
    private final IControlClientes cliente;
    private final IControlCreacionUI creacion;
    
    

    public PantallaGenerarPresupuesto(IControlNavegacion navegacion, IControlOrdenes orden, IControlClientes cliente, IControlCreacionUI creacion) {
        initComponents();
        configurarVentana();
        this.navegacion = navegacion;
        this.orden = orden;
        this.cliente = cliente;
        this.creacion = creacion;
        
        
    }

        private void configurarVentana() {
         this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2_Refacciones = new javax.swing.JScrollPane();
        jScrollPane1_Orden = new javax.swing.JScrollPane();
        jScrollPane3_Servicios = new javax.swing.JScrollPane();
        btnRegresar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jScrollPane2_Refacciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 310, 100));
        getContentPane().add(jScrollPane1_Orden, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 220, 340));
        getContentPane().add(jScrollPane3_Servicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 310, 100));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonRegresar.png"))); // NOI18N
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 50));

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonSiguiente.png"))); // NOI18N
        btnSiguiente.setContentAreaFilled(false);
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 460, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PantallaGenerarPresupuestoCUA.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
       navegacion.mostrarPantallaPresupuestoGenerado();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
//        navegacion.mostrarPantallaSeleccionarOrden(clienteDTO);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JScrollPane jScrollPane1_Orden;
    private javax.swing.JScrollPane jScrollPane2_Refacciones;
    private javax.swing.JScrollPane jScrollPane3_Servicios;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
