/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.GenerarPresupuesto;

import dto.ClienteDTO;
import dto.PresupuestoDTO;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import presentacion.controles.IControlClientes;
import presentacion.controles.IControlCreacionUI;
import presentacion.controles.IControlNavegacion;
import presentacion.controles.IControlOrdenes;
import presentacion.controles.IControlPresupuestos;

/**
 *
 * @author Pride Factor Black
 */
public class PantallaSeleccionarCliente extends javax.swing.JFrame {
    private final IControlNavegacion navegacion;
    private final IControlClientes clientes;
    private final IControlCreacionUI creacion;
    private final IControlPresupuestos control;
    private final IControlOrdenes orden;
    private final IControlPresupuestos presupuesto;
    /**
     * Creates new form PantallaSeleccionarCliente
     */
    public PantallaSeleccionarCliente( IControlNavegacion navegacion, IControlClientes clientes, IControlCreacionUI creacion, IControlPresupuestos control, IControlOrdenes orden, IControlPresupuestos presupuesto) {
        initComponents();
        configurarVentana();
        this.navegacion = navegacion;
        this.control= control;
        this.clientes = clientes;
        this.creacion = creacion;
        this.orden= orden; 
        this.presupuesto=presupuesto;
        
        
        generarListaClientes();
        
        scrollPaneClientes.setOpaque(false);
        scrollPaneClientes.getViewport().setOpaque(false);
        scrollPaneClientes.setBorder(null);
        scrollPaneClientes.getViewport().setBorder(null);
    }

    private void generarListaClientes() {
        List<ClienteDTO> listaClientes = clientes.buscarTodosLosClientesActivos();

        JPanel contenedor = new JPanel();
        contenedor.setLayout(new BoxLayout(contenedor, BoxLayout.Y_AXIS));
        contenedor.setOpaque(false);

        for (ClienteDTO clienteDTO : listaClientes) {

            String texto = clienteDTO.getNombre() + " "
                    + clienteDTO.getApellidoP() + " "
                    + clienteDTO.getApellidoM() + " | "
                    + clienteDTO.getTelefono();

            JPanel panel = creacion.crearPanelCliente(texto);

            panel.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    clienteSeleccionado(clienteDTO);
                }
            });

            contenedor.add(panel);
        }

        scrollPaneClientes.setViewportView(contenedor);
    }
    
    private void clienteSeleccionado(ClienteDTO cliente) {
        navegacion.mostrarPantallaSeleccionarOrden(orden, creacion, cliente);
        this.dispose();
}
     
      private void configurarVentana() {
        this.setLocationRelativeTo(null);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        scrollPaneClientes = new javax.swing.JScrollPane();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 150, 30));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnBuscar (1).png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 30, 30));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonRegresar.png"))); // NOI18N
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));
        getContentPane().add(scrollPaneClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 460, 260));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PantallaSeleccionarClienteCUA.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        navegacion.mostrarMenuPrincipal();
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JScrollPane scrollPaneClientes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
